# Generated by Django 5.1.1 on 2024-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
